### ISSUE TITLE
experimenting with poseNet/gestures/WiiRemotes

### ISSUE THREAD

**Issue by LauraWyffels** [LauraWyffels/EXW#8]

**Comment by Sjouwke** [comment]
Redelijk ingewikkeld precies eh? Ik heb wel net een app gevonden en daarbij beweegt ge gewoon in de richting da ge kijkt, en da is eigenlijk wel nog tof. Dan hebben we nie per se een andere remote nog nodig (buiten de knop op ons cardboard voor vb iets te selecteren of zo).
